# Generated by Django 5.0.2 on 2024-03-01 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistName', models.CharField(max_length=255)),
                ('artistBday', models.CharField(max_length=255)),
                ('artistGenere', models.CharField(max_length=255)),
                ('artistPlatform', models.CharField(max_length=255)),
                ('artistImage', models.ImageField(default='avatar.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festivalName', models.CharField(max_length=255)),
                ('festivalInfo', models.TextField()),
                ('festivalImage', models.ImageField(default='pexels-alexander-suhorucov-6457579.jpg', upload_to='')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.artist')),
            ],
        ),
    ]
