# Generated by Django 5.0.2 on 2024-03-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventTime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventDate',
            field=models.DateField(null=True),
        ),
    ]
