# Generated by Django 5.0.2 on 2024-03-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_event_eventtime_alter_event_eventdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='eventTime',
        ),
        migrations.AddField(
            model_name='event',
            name='eventEnd',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='eventStart',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
