# Generated by Django 5.0.2 on 2024-03-02 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_remove_event_eventtime_event_eventend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='artistName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.artist'),
        ),
    ]
