# Generated by Django 5.0.2 on 2024-03-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_event_artistname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketFullName', models.CharField(max_length=100)),
                ('ticketEmail', models.EmailField(max_length=254, unique=True)),
                ('ticketPhone', models.CharField(max_length=15)),
                ('ticketType', models.CharField(choices=[('early-bird', 'Early bird'), ('standard', 'Standard')], max_length=20)),
                ('ticketRequest', models.TextField()),
            ],
        ),
    ]
