# Generated by Django 5.0.2 on 2024-03-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_ticket_ticketrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticketRequest',
            field=models.TextField(blank=True, null=True),
        ),
    ]
