# Generated by Django 5.0.2 on 2024-03-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_ticket_ticketrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageFullName', models.CharField(max_length=100)),
                ('messageEmail', models.EmailField(max_length=254)),
                ('messageSuggestion', models.TextField()),
            ],
        ),
    ]
